/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, IsOptional, IsEnum, IsJSON } from "class-validator";
import { EnumCardCardType } from "./EnumCardCardType";
import { GraphQLJSONObject } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { EnumCardRarity } from "./EnumCardRarity";
@InputType()
class CardCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  cardImage?: string | null;

  @ApiProperty({
    required: false,
    enum: EnumCardCardType,
  })
  @IsEnum(EnumCardCardType)
  @IsOptional()
  @Field(() => EnumCardCardType, {
    nullable: true,
  })
  cardType?: "monster" | "hero" | null;

  @ApiProperty({
    required: false,
  })
  @IsJSON()
  @IsOptional()
  @Field(() => GraphQLJSONObject, {
    nullable: true,
  })
  equippableModifier?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  equippedImage?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  flavorText?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsJSON()
  @IsOptional()
  @Field(() => GraphQLJSONObject, {
    nullable: true,
  })
  nonEquippableModifier?: InputJsonValue;

  @ApiProperty({
    required: false,
    enum: EnumCardRarity,
  })
  @IsEnum(EnumCardRarity)
  @IsOptional()
  @Field(() => EnumCardRarity, {
    nullable: true,
  })
  rarity?: "common" | "uncommon" | "rare" | "legendary" | null;
}
export { CardCreateInput };
